# Generated by Django 3.0.4 on 2020-03-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0003_auto_20200316_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answervote',
            old_name='question',
            new_name='answer',
        ),
    ]
