# Generated by Django 3.0.4 on 2020-03-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0004_auto_20200316_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answervote',
            old_name='answer',
            new_name='to',
        ),
        migrations.RenameField(
            model_name='questionvote',
            old_name='question',
            new_name='to',
        ),
    ]
