# Generated by Django 3.0.4 on 2020-03-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0006_auto_20200316_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingMixin',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='qanda.Answer'),
        ),
    ]
